### ISSUE TITLE
Exception when calling /monitoring/info (VersionContributor) on localhost

### ISSUE THREAD

**Issue by datazuul** [dbmdz/digitalcollections-commons#2]
```
java.lang.IllegalArgumentException: Could not resolve placeholder 'scmBranch' in value "1.0.0-SNAPSHOT manually built by ralf (2018-03-12 10:21:38, branch ${scmBranch}, commit ${buildNumber} maybe with modifications)"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:172)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
	at org.springframework.boot.context.properties.bind.PropertySourcesPlaceholdersResolver.resolvePlaceholders(PropertySourcesPlaceholdersResolver.java:60)
	at org.springframework.boot.context.properties.bind.Binder.bindProperty(Binder.java:320)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:267)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:221)
	at org.springframework.boot.context.properties.bind.Binder.lambda$null$0(Binder.java:301)
	at org.springframework.boot.context.properties.bind.Binder$Context.withSource(Binder.java:410)
	at org.springframework.boot.context.properties.bind.Binder$Context.access$900(Binder.java:379)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$1(Binder.java:303)
	at org.springframework.boot.context.properties.bind.AggregateElementBinder.bind(AggregateElementBinder.java:39)
	at org.springframework.boot.context.properties.bind.MapBinder$EntryBinder.lambda$bindEntries$0(MapBinder.java:121)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at org.springframework.boot.context.properties.bind.MapBinder$EntryBinder.bindEntries(MapBinder.java:120)
```

**Comment by datazuul** [comment]
not reproducable
