### ISSUE TITLE
Support for XPath functions

### ISSUE THREAD

**Issue by clorenz** [dbmdz/digitalcollections-commons#289]
We need support for XPath functions to evaluate XPath expressions like the following:
```
substring(/TEI/teiHeader/fileDesc/notesStmt/note[@type="digDate"]/date[@ana="#scan"]/@when,1,10)
```

Currently, an Exception is thrown:
```
[...]
Caused by: javax.xml.xpath.XPathExpressionException: net.sf.saxon.trans.XPathException: Cannot convert XPath value to Java object: required class is org.w3c.dom.NodeList; supplied value has type xs:string
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:244)
	at de.digitalcollections.commons.xml.xpath.XPathWrapper.evaluateXpath(XPathWrapper.java:187)
	... 126 more
Caused by: net.sf.saxon.trans.XPathException: Cannot convert XPath value to Java object: required class is org.w3c.dom.NodeList; supplied value has type xs:string
	at net.sf.saxon.dom.DOMObjectModel.convertXPathValueToObject(DOMObjectModel.java:420)
	at net.sf.saxon.dom.DOMObjectModel$7.convert(DOMObjectModel.java:202)
	at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:239)
``

**Comment by jbaiter** [comment]
Der Support ist drin, da wir ja Saxon verwenden (siehe Fehlermeldung). Das Problem ist nicht dass Funktionen nicht unterstützt werden, sondern dass das XPath-Resultat in eine `NodeList` Variable gespeichert werden soll, was aber nicht möglch ist da der Ausdruck einen `xs:string` zurück gibt, der kann natürlrich nicht als `NodeList` gespeichert werden.

Um das zu lösen bräuchte ich den gesamten Code-Abschnitt der den XPath-Ausdruck verwendet.

**Comment by clorenz** [comment]
Ein beispielhafter Anwendungsfall wäre:
`@XPathBinding("substring(/TEI/teiHeader/fileDesc/notesStmt/note[@type=\"digDate\"]/date[@ana=\"#scan\"]/@when,1,10)")`
